-- One row per funding run (the audit-trail header).
CREATE TABLE funding_request (
    id                           UUID                     NOT NULL,
    available_settlement_balance NUMERIC(19, 2)           NOT NULL,
    total_settlement_consumed    NUMERIC(19, 2)           NOT NULL,
    total_expected_fee           NUMERIC(19, 2)           NOT NULL,
    candidate_count              INTEGER                  NOT NULL,
    selected_count               INTEGER                  NOT NULL,
    created_at                   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_funding_request PRIMARY KEY (id),
    CONSTRAINT chk_funding_request_balance CHECK (available_settlement_balance >= 0),
    CONSTRAINT chk_funding_request_consumed CHECK (
        total_settlement_consumed >= 0 AND total_settlement_consumed <= available_settlement_balance),
    CONSTRAINT chk_funding_request_counts CHECK (selected_count >= 0 AND selected_count <= candidate_count)
);

-- Audit listing is "newest first, paginated"; id is the tie-breaker for a stable order.
CREATE INDEX idx_funding_request_created_at ON funding_request (created_at DESC, id DESC);

-- Every candidate instruction submitted with a run, flagged with whether it was selected.
-- Storing the rejected ones too lets the desk audit *why* a selection was made.
CREATE TABLE funding_instruction (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    request_id            UUID           NOT NULL,
    input_order           INTEGER        NOT NULL,
    instruction_reference VARCHAR(128)   NOT NULL,
    instruction_amount    NUMERIC(19, 2) NOT NULL,
    expected_fee          NUMERIC(19, 2) NOT NULL,
    selected              BOOLEAN        NOT NULL,
    CONSTRAINT pk_funding_instruction PRIMARY KEY (id),
    CONSTRAINT fk_funding_instruction_request FOREIGN KEY (request_id)
        REFERENCES funding_request (id) ON DELETE CASCADE,
    CONSTRAINT uq_funding_instruction_reference UNIQUE (request_id, instruction_reference),
    CONSTRAINT chk_funding_instruction_amount CHECK (instruction_amount > 0),
    CONSTRAINT chk_funding_instruction_fee CHECK (expected_fee >= 0)
);

-- Children are always loaded per request in input order; this index serves that lookup
-- and also backs the foreign key.
CREATE INDEX idx_funding_instruction_request ON funding_instruction (request_id, input_order);
